// <auto-generated />
using System;
using System.Collections.Generic;
using McpGateway.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace McpGateway.Persistence.Migrations
{
    [DbContext(typeof(McpGatewayDbContext))]
    partial class McpGatewayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ai_gateway")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("McpGateway.Persistence.Entities.GatewayApiKeyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_hash");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_prefix");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.PrimitiveCollection<List<string>>("Scopes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("scopes");

                    b.Property<Guid>("ServerDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_definition_id");

                    b.HasKey("Id")
                        .HasName("pk_gateway_api_keys");

                    b.HasIndex("KeyPrefix")
                        .HasDatabaseName("ix_gateway_api_keys_key_prefix")
                        .HasFilter("revoked_at IS NULL");

                    b.HasIndex("ServerDefinitionId")
                        .HasDatabaseName("ix_gateway_api_keys_server_definition_id");

                    b.ToTable("gateway_api_keys", "ai_gateway");
                });

            modelBuilder.Entity("McpGateway.Persistence.Entities.McpServerDefinitionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pending")
                        .HasColumnName("approval_status");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text")
                        .HasColumnName("approved_by");

                    b.Property<string>("AuthConfig")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("{}")
                        .HasColumnName("auth_config");

                    b.Property<string>("AuthStrategy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth_strategy");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("base_url");

                    b.Property<string>("ClientProfile")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("universal")
                        .HasColumnName("client_profile");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<DateTime?>("LastRefreshedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_refreshed_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("PollIntervalMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1440)
                        .HasColumnName("poll_interval_minutes");

                    b.Property<string>("SpecContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("spec_content");

                    b.Property<string>("SpecHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("spec_hash");

                    b.Property<string>("SpecSourceUrl")
                        .HasColumnType("text")
                        .HasColumnName("spec_source_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<string>("ToolMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("all")
                        .HasColumnName("tool_mode");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_mcp_server_defs");

                    b.HasIndex("ApprovalStatus")
                        .HasDatabaseName("ix_mcp_server_defs_approval_status")
                        .HasFilter("approval_status = 'approved'");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_mcp_server_defs_name");

                    b.ToTable("mcp_server_defs", "ai_gateway");
                });

            modelBuilder.Entity("McpGateway.Persistence.Entities.SpecVersionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DiffSummary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("diff_summary");

                    b.Property<Guid>("ServerDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_definition_id");

                    b.Property<string>("SpecContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("spec_content");

                    b.Property<string>("SpecHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("spec_hash");

                    b.Property<int>("ToolCount")
                        .HasColumnType("integer")
                        .HasColumnName("tool_count");

                    b.HasKey("Id")
                        .HasName("pk_spec_versions");

                    b.HasIndex("ServerDefinitionId", "CreatedAt")
                        .HasDatabaseName("ix_spec_versions_server_definition_id_created_at");

                    b.ToTable("spec_versions", "ai_gateway");
                });

            modelBuilder.Entity("McpGateway.Persistence.Entities.ToolEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthConfig")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("{}")
                        .HasColumnName("auth_config");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("http_method");

                    b.Property<string>("HttpPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("http_path");

                    b.Property<string>("InputSchema")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("input_schema");

                    b.Property<string>("OutputSchema")
                        .HasColumnType("text")
                        .HasColumnName("output_schema");

                    b.Property<Guid>("ServerDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_definition_id");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tool_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("Visible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("visible");

                    b.HasKey("Id")
                        .HasName("pk_tools");

                    b.HasIndex("ServerDefinitionId")
                        .HasDatabaseName("ix_tools_server_definition_id");

                    b.HasIndex("ServerDefinitionId", "ToolName")
                        .IsUnique()
                        .HasDatabaseName("ix_tools_server_definition_id_tool_name");

                    b.ToTable("tools", "ai_gateway");
                });

            modelBuilder.Entity("McpGateway.Persistence.Entities.ToolOverrideEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DescriptionOverride")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_override");

                    b.Property<Guid>("ServerDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_definition_id");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tool_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("Visible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("visible");

                    b.HasKey("Id")
                        .HasName("pk_tool_overrides");

                    b.HasIndex("ServerDefinitionId", "ToolName")
                        .IsUnique()
                        .HasDatabaseName("ix_tool_overrides_server_definition_id_tool_name");

                    b.ToTable("tool_overrides", "ai_gateway");
                });

            modelBuilder.Entity("McpGateway.Persistence.Entities.GatewayApiKeyEntity", b =>
                {
                    b.HasOne("McpGateway.Persistence.Entities.McpServerDefinitionEntity", "ServerDefinition")
                        .WithMany("GatewayApiKeys")
                        .HasForeignKey("ServerDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gateway_api_keys_server_definitions_server_definition_id");

                    b.Navigation("ServerDefinition");
                });

            modelBuilder.Entity("McpGateway.Persistence.Entities.SpecVersionEntity", b =>
                {
                    b.HasOne("McpGateway.Persistence.Entities.McpServerDefinitionEntity", "ServerDefinition")
                        .WithMany("SpecVersions")
                        .HasForeignKey("ServerDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spec_versions_server_definitions_server_definition_id");

                    b.Navigation("ServerDefinition");
                });

            modelBuilder.Entity("McpGateway.Persistence.Entities.ToolEntity", b =>
                {
                    b.HasOne("McpGateway.Persistence.Entities.McpServerDefinitionEntity", "ServerDefinition")
                        .WithMany("Tools")
                        .HasForeignKey("ServerDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tools_server_definitions_server_definition_id");

                    b.Navigation("ServerDefinition");
                });

            modelBuilder.Entity("McpGateway.Persistence.Entities.ToolOverrideEntity", b =>
                {
                    b.HasOne("McpGateway.Persistence.Entities.McpServerDefinitionEntity", "ServerDefinition")
                        .WithMany("ToolOverrides")
                        .HasForeignKey("ServerDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tool_overrides_server_definitions_server_definition_id");

                    b.Navigation("ServerDefinition");
                });

            modelBuilder.Entity("McpGateway.Persistence.Entities.McpServerDefinitionEntity", b =>
                {
                    b.Navigation("GatewayApiKeys");

                    b.Navigation("SpecVersions");

                    b.Navigation("ToolOverrides");

                    b.Navigation("Tools");
                });
#pragma warning restore 612, 618
        }
    }
}
